    pets = [
        [1,1,"Lucky","M", Date.new(2012,01,01)," ","Y"," "," "," ","No teeth"," ","White","Bichon",15],
        [2,1,"Flynn","M",Date.new(2017,01,01)," ","N"," ","VCA Spring Branch"," "," ","Growls on nails, nervous but good boy"," ","Terrier Mix",56],
        [3,1,"Oreo","F",Date.new(2018,01,01)," ","N"," ","Kaaws"," "," "," "," "," "," "],
        [4,1,"Remy","M",Date.new(2017,01,01)," ","N"," "," "," "," "," "," ","Maltese"," "],
        [5,1,"Henny"," ",Date.new(2018,01,01)," ","N"," ","The Vet","972-675-2510"," "," ","Black, White, Brown","English Bulldog",44],
        [6,1,"Kookie","F",nil," ","N"," "," "," "," ","Hates nails, bites when picked up"," ","Mixed Shih Tzu"," "],
        [7,1,"Bowser Nguyen","M",Date.new(2019,01,01)," ","N"," ","Cypress Square Animal Clinic"," "," ","Shy, scared"," ","Mini Schnauzer"," "],
        [8,1,"Bentley","M",nil," ","N"," ","Kaaws"," "," "," "," ","Shih Tzu"," "],
        [9,1,"Boy","M",Date.new(2019,01,01)," ","N"," "," "," "," "," "," "," ",76],
        [10,1,"Rudolph","M",Date.new(2013,01,01),"Y","N"," ","Cypress Square Animal Clinic"," "," "," ","White","Maltipoo",15],
        [11,1,"Eevee","F",nil," ","N"," "," "," "," ","Poppy & Fluffy's daughter","Black, White","Shih Tzu, Maltipoo"," "],
        [12,1,"Teddy","M",Date.new(2012,01,01)," ","N"," "," "," "," "," "," ","Poodle"," "],
        [13,1,"Gigi","F",nil," ","N"," ","Pet Care Express"," "," ","Puppy"," ","Shih Tzu, Maltese"," "],
        [14,1,"Kirby","M",Date.new(2019,01,01)," ","Y"," ","Wainwright"," "," "," ","Tan","Terrier",13],
        [14,1,"Bailey","M",Date.new(2003,01,01)," ","N"," "," "," "," ","In Heaven"," ","Shih Tzu"," "],
        [15,1,"Sandie","F",Date.new(2013,01,01)," ","Y"," "," "," "," "," ","Brown","Terrier Mix",22],
        [16,1,"Newton","M",Date.new(2018,01,01)," ","Y"," "," "," "," ","Very hard to groom","White","Cocker Spaniel",19],
        [17,1,"Maggie","F",Date.new(2018,01,01)," ","Y"," ","Hearthstone AC (529/Huff)"," "," "," ","Blonde","Golden Doodle",76],
        [18,1,"Chloe","F",Date.new(2018,01,01)," ","N"," "," "," "," "," "," ","Chi Mix"," "],
        [19,1,"Ziegenbock","F",Date.new(2015,10,11)," ","Y"," ","Dr. Blonien"," "," ","Jumpy"," "," "," "],
        [20,1,"Arnold","M",Date.new(2017,01,01)," ","Y"," ","Kaaws"," "," "," ","Cream","Shih Tzu Mix",16],
        [21,1,"Jolie","F",Date.new(2015,01,01)," "," "," "," "," "," ","Doesn't like nail cut"," ","Shih Tzu"," "],
        [22,1,"Oscar","M",nil," "," "," ","Corner Vet"," "," "," "," "," "," "],
        [22,1,"Cleo ","M",Date.new(2012,01,01)," "," ","N","Hight Vet"," "," ","Don't cut ear hair, Do not feed"," ","Cairn Terrier"," "],
        [23,1,"Peanut","M",nil," "," "," "," "," "," "," ","Tan","Pom"," "],
        [24,1,"Toby","M",Date.new(2016,01,01)," "," "," "," "," "," "," "," ","Chihuahua/Terrier"," "],
        [25,1,"Zeppelin","M",Date.new(2014,01,01)," "," "," "," "," "," "," "," ","Aussie Mix",36],
        [26,1,"Luna Belle","F",Date.new(2011,01,01)," "," "," ","Jersey Village Animal Hospital"," "," "," "," ","Terrier Mix"," "],
        [27,1,"Ching Shi","F",nil," "," "," "," "," "," "," ","Black, White"," ",17],
        [27,1,"Shing Lee","M",nil," "," "," "," "," "," ","Hates doing nail cut"," ","Shih Tzu",20],
        [27,1,"Korkie","M",nil," "," "," "," "," "," "," "," ","Schnauzer"," "],
        [28,1,"Emma","F",Date.new(2008,01,01)," ","Y"," "," "," "," "," ","White,Cream","Cocker Bichon"," "],
        [29,1,"Murphy","M",Date.new(2014,04,01)," ","Y"," ","Cypress Square Animal Clinic"," "," "," "," ","Pembroke Corgi"," "],
        [30,1,"Sydney","F",nil," "," "," ","Larry White"," "," ","Good on grooming"," ","Maltipoo"," "],
        [31,1,"Harley","M",Date.new(2017,01,01)," ","Y"," ","Tx Coalition"," "," "," ","Black","Lhasa",18],
        [32,1,"Pepe le Pew","M",nil," "," "," "," "," "," ","Bossy"," ","Pomeranian"," "],
        [32,1,"Valentine","M",nil," "," "," "," ",713-291-1702," ","Scared easily"," ","Mini Schnauzer"," "],
        [32,1,"Layla","F",nil," "," "," ","Dr. Ken"," "," "," "," ","Weiner dog"," "],
        [32,1,"Chimmie","M",nil," "," "," "," "," "," "," "," ","Weiner dog"," "],
        [33,1,"Bailey","F",Date.new(2017,01,01)," "," "," ","Tanner Lakes"," "," "," ","White, Gray","Old English"," "],
        [33,1,"Millie","F",Date.new(2010,01,01)," "," "," ","Tanner Lakes"," "," "," ","White, Brown","Bishon"," "],
        [34,1,"Coco","F",Date.new(2013,01,01)," "," "," ","St. Francis"," "," "," "," ","Terrier Mix"," "],
        [34,1,"Callie","F",Date.new(2015,01,01)," "," "," ","St. Francis"," "," "," ","Black,White","King Charles"," "],
        [35,1,"Stanley","M",Date.new(2016,01,01)," "," "," ","Tanner Lakes"," "," ","Shy,noisy"," ","Yorkie"," "],
        [35,1,"Jake","M",Date.new(2015,01,01)," "," "," ","Tanner Lakes"," "," ","Shy,noisy"," ","Yorkie"," "],
        [35,1,"Sara","F",Date.new(2017,01,01)," "," "," ","Tanner Lakes"," "," ","Shy,noisy"," ","Yorkie"," "],
        [36,1,"Pinky","F",nil," "," "," "," "," "," "," "," ","Maltipoo"," "],
        [37,1,"Cherry","F",Date.new(2016,01,01)," "," "," ","Crossroads Vet"," "," "," "," "," "," "],
        [38,1,"Rylie","F",Date.new(2015,01,01)," "," "," ","Jersey Village Animal Hospital"," "," "," ","Tan","Lab Mix",25],
        [39,1,"Barter","F",Date.new(2014,01,01)," "," "," "," "," "," "," "," ","Pug"," "],
        [40,1,"Jammy","M",Date.new(2015,01,01)," "," "," ","Dr. Martin Kaedle"," "," ","Noisy","White","Mini Schnauzer"," "],
        [40,1,"Sterling","M",Date.new(2015,01,02)," "," "," ","Dr. Martin Kaedle"," "," "," ","Gray","Mini Schnauzer"," "],
        [41,1,"Cookie","M",Date.new(2012,01,01)," "," "," "," "," "," "," "," ","Yorkie Poo",16],
        [42,1,"Pixie","F",Date.new(2010,01,01)," "," "," "," "," "," "," "," ","Chihuahua",7],
        [43,1,"Sunny","F",Date.new(2016,01,01)," "," "," ","Kingsland Vet Clinic"," "," "," "," ","Poodle Mix"," "],
        [43,1,"Jax","M",Date.new(2010,01,01)," "," "," ","Kingsland Vet Clinic"," "," "," "," "," "," "],
        [44,1,"Kaysi","F",Date.new(2018,01,01)," "," "," "," "," "," "," ","Brown","Shih Tzu"," "],
        [46,1,"Barkley","M",nil," "," "," "," "," "," "," "," ","Maltese"," "],
        [47,1,"Bruce","M",Date.new(2016,06,01)," ","y"," ","Dr. Cheryl Morales"," "," "," ","Black","Mix",42],
        [48,1,"Pancho","M",Date.new(2014,11,01)," ","N"," "," "," "," "," ","Brown","Chihuahua",12],
        [49,1,"Lucky","M",Date.new(2018,01,01)," ","N"," "," "," "," "," ","Tan","Maltese Mix"," "],
        [50,1,"Corette","F",Date.new(2013,01,01)," ","y"," "," "," "," "," ","Blonde","Shih Tzu",12],
        [51,1,"Pooh Bear","M",Date.new(2017,11,01)," "," "," "," "," "," "," "," ","Golden Retriever",78],
        [51,1,"Bud","M",nil," ","N"," "," "," "," ","Pooh Bear Family","Black, Tan","Yorkie"," "],
        [52,1,"Izzy","F",nil," ","N"," ","Longendauch Vet"," "," ","Scared of water"," ","German Shepherd Mix"," "],
        [53,1,"Leo","M",nil," "," "," "," "," "," "," "," "," "," "],
        [54,1,"Lydia","F",Date.new(2011,12,01)," ","Y"," "," "," "," "," ","White","Golden Retriever",49],
        [54,1,"Millie","F",Date.new(2005,12,01),"Y"," "," "," "," "," "," ","Brown, Red","Golden Retriever"," "],
        [55,1,"Pillow","F",Date.new(2011,07,01)," "," "," "," "," "," "," "," ","Golden Retriever"," "],
        [56,1,"Baccarat","M",nil," "," "," "," "," "," "," "," ","Shih Tzu"," "],
        [57,1,"Brownie","M",Date.new(2008,01,01)," "," "," ","Affordable Pet Care"," "," ","Bites when he is scared. Noisy"," ","Dachshund"," "],
        [58,1,"Jools","F",Date.new(2018,01,01)," ","Y"," ","Canfel"," "," "," ","Tan","Terrier"," "],
        [58,1,"Emmie","F",nil," ","Y"," ","Canfel"," "," ","Little girl","Tan"," "," "],
        [58,1,"Sadie","F",nil," "," "," ","Wainwright"," ","Epileptic","In Heaven"," ","Pomapoo"," "],
        [59,1,"Xena","F",nil," "," "," "," "," "," ","Shy. Bites"," ","Terrier Mix"," "],
        [59,1,"Griffin","M",Date.new(2019,01,01)," "," "," "," "," "," "," ","White","Terrier"," "],
        [60,1,"Bentley","M",Date.new(2018,02,01)," ","N"," "," "," ","N/A"," ","White","Maltipoo",36],
        [61,1,"Eliot","M",Date.new(2014,11,01)," "," "," ","Hearthstone Clinic"," "," "," ","White","Westie",16],
        [61,1,"Oliver","M",Date.new(2009,07,01)," ","Y"," "," "," "," "," ","White","Westie",20],
        [62,1,"Prince","M",Date.new(2014,01,01)," ","Y"," ","Thrive"," "," "," "," ","Maltipoo"," "],
        [62,1,"Lala","F",Date.new(2016,01,01)," ","Y"," "," "," "," "," "," ","Maltese"," "],
        [63,1,"Jinx","F",Date.new(2017,11,01)," ","Y"," ","Lonestar Vetinary"," ","None"," "," "," ",45],
        [64,1,"Sir Angus Hamilton","M",Date.new(2013,9,26)," "," "," "," "," "," ","Noisy, Shy, Doesn't like nails done"," ","Scottie",26],
        [64,1,"Dougal","M",Date.new(2018,05,01)," ","N"," "," "," "," "," ","Black","Scottie",25],
        [65,1,"Pita","F",Date.new(2017,06,01)," ","Y"," "," "," "," "," ","Tan","Lab Mix",60],
        [65,1,"Tahwi","F",Date.new(2017,06,02)," ","Y"," "," "," "," "," ","Tan"," ",50],
        [66,1,"Stevie","M",nil," "," "," ","Dr. Smih Clay Rd"," ","Blind","Bites"," ","Shih Tzu"," "],
        [66,1,"Nellie","F",Date.new(2003,01,01)," "," "," "," "," "," ","In Heaven","Brown","Chihuahua"," "],
        [66,1,"Punk","F",Date.new(2002,01,01)," "," "," "," "," "," Arthritic, Epileptic","In Heaven "," ","Chihuahua"," "],
        [66,1,"Daisy","F",nil," "," "," "," "," "," "," "," ","Terrier Mix"," "],
        [66,1,"Valentina","F",nil," "," "," "," "," "," ","Shy"," "," "," "],
        [66,1,"Milo","M",Date.new(2014,8,01)," "," "," "," "," "," "," "," ","Bulldog Mix"," "],
        [45,1,"Chibi","F",Date.new(2018,01,01)," "," "," ","Tanner Lakes",713-937-4484," "," "," ","Mini Dachshund"," "],
        [67,1,"Angel","F",nil," "," "," "," "," "," "," "," ","Bichon Poodle"," "],
        [68,1,"Cooper","M",Date.new(2013,01,01)," "," "," ","Glen Cairn Animal Clinic"," ","No"," ","Black","Lab",75],
        [68,1,"Mija","F",Date.new(2010,01,01)," ","Y"," ","Clen Cairn Animal Clinic"," ","No"," ","Black","Lab",80],
        [69,1,"Sawyer","M",Date.new(2010,01,01)," "," "," ","Natalie Goldberger"," "," "," ","Gold","Snoodle",22],
        [70,1,"Bruno","F",Date.new(2012,01,01)," "," "," ","Kawws"," "," "," ","White","Poodle",20],
        [71,1,"Teddy","M",nil," "," "," "," ",832-549-3123," "," "," ","Chihuahua Mix"," "],
        [74,1,"Sysco","M",Date.new(2009,01,01)," "," "," ","Tanner Lakes"," "," "," "," ","Havanese"," "]
    ]



    pets.each do | customer_id, pet_status_id, name, gender, birthdate, allergies, sn, treat, vet_name, vet_phone, med_issues, notes, color, breed, weight|
        Pet.create( customer_id: customer_id, pet_status_id: pet_status_id, pet_name: name, pet_gender: gender, pet_birthdate: birthdate, pet_allergies: allergies,
                    spayed_neutered: sn, pet_treat: treat, vet_name: vet_name, vet_phone: vet_phone, pet_medical_issues: med_issues, pet_notes: notes, pet_color: color,
                    pet_breed: breed, pet_weight: weight)
    end

