    pets = [
        [1,1,"Lucky","M", Date.new(2012,01,01)," ","Y","Y"," "," ","No teeth"," ","White","Bichon",15],
        [2,1,"Flynn","M",Date.new(2017,01,01)," ","N","N","VCA Spring Branch"," "," ","Growls on nails, nervous but good boy","Mix ","Terrier Mix",56],
        [3,1,"Oreo","F",Date.new(2018,01,01)," ","N","N","Kaaws"," "," "," ","Brown","Lab Mix",20],
        [4,1,"Remy","M",Date.new(2017,01,01)," ","N","Y"," "," "," "," ","Sandy","Maltese",20],
        [5,1,"Henny","M",Date.new(2018,01,01)," ","N","N","The Vet","972-675-2510"," "," ","Black, White, Brown","English Bulldog",44],
        [6,1,"Kookie","F",nil," ","N","Y"," "," "," ","Hates nails, bites when picked up","Browm, White","Mixed Shih Tzu",20],
        [7,1,"Bowser Nguyen","M",Date.new(2019,01,01)," ","N","Y","Cypress Square Animal Clinic"," "," ","Shy, scared","Grey, White","Mini Schnauzer",20],
        [8,1,"Bentley","M",nil," ","N","Y","Kaaws"," "," "," ","Black, Brown, White","Shih Tzu",20],
        [9,1,"Boy","M",Date.new(2019,01,01)," ","N","N"," "," "," "," ","Brown, White","Lab/Pit",76],
        [10,1,"Rudolph","M",Date.new(2013,01,01)," ","N","N","Cypress Square Animal Clinic"," "," "," ","White","Maltipoo",15],
        [11,1,"Eevee","F",nil," ","N","Y"," "," "," ","Poppy & Fluffy's daughter","Black, White","Shih Tzu, Maltipoo",20],
        [12,1,"Teddy","M",Date.new(2012,01,01)," ","N","N"," "," "," "," ","White","Poodle",20],
        [13,1,"Gigi","F",nil," ","N","Y","Pet Care Express"," "," ","Puppy","Black","Shih Tzu, Maltese",20],
        [14,1,"Kirby","M",Date.new(2019,01,01)," ","Y","N","Wainwright"," "," "," ","Tan","Terrier",13],
        [14,2,"Bailey","M",Date.new(2003,01,01)," ","N","Y"," "," "," ","In Heaven","Brown","Shih Tzu",20],
        [15,1,"Sandie","F",Date.new(2013,01,01)," ","Y","N"," "," "," "," ","Brown","Terrier Mix",22],
        [16,1,"Newton","M",Date.new(2018,01,01)," ","Y","Y"," "," "," ","Very hard to groom","White","Cocker Spaniel",19],
        [17,1,"Maggie","F",Date.new(2018,01,01)," ","Y","N","Hearthstone AC (529/Huff)"," "," "," ","Blonde","Golden Doodle",76],
        [18,1,"Chloe","F",Date.new(2018,01,01)," ","N","Y"," "," "," "," ","Black","Chi Mix",20],
        [19,1,"Ziegenbock","F",Date.new(2015,10,11)," ","Y","Y","Dr. Blonien"," "," ","Jumpy","Black,Brown,Grey","Chihuaua, Dachsund",20],
        [20,1,"Arnold","M",Date.new(2017,01,01)," ","Y","N","Kaaws"," "," "," ","Cream","Shih Tzu Mix",16],
        [21,1,"Jolie","F",Date.new(2015,01,01)," ","Y","N"," "," "," ","Doesn't like nail cut","Brown","Shih Tzu",20],
        [22,1,"Oscar","M",nil," ","Y","Y","Corner Vet"," "," "," ","Black, Brown","Aussie, Pit",20],
        [22,1,"Cleo ","M",Date.new(2012,01,01)," ","Y","N","Hight Vet"," "," ","Don't cut ear hair, Do not feed","White, Black","Cairn Terrier",20],
        [23,1,"Peanut","M",nil," ","Y","N"," "," "," "," ","Tan","Pom",20],
        [24,1,"Toby","M",Date.new(2016,01,01)," ","Y","Y"," "," "," "," ","Brown","Chihuahua/Terrier",20],
        [25,1,"Zeppelin","M",Date.new(2014,01,01)," ","Y","N"," "," "," "," ","Brown, Grey, White","Aussie Mix",36],
        [26,1,"Luna Belle","F",Date.new(2011,01,01)," ","Y","N","Jersey Village Animal Hospital"," "," "," ","White, Brown","Terrier Mix",20],
        [27,1,"Ching Shi","F",nil," ","Y","Y"," "," "," "," ","Black, White","Poodle Mix",17],
        [27,1,"Shing Lee","M",nil," ","N","Y"," "," "," ","Hates doing nail cut","Black","Shih Tzu",20],
        [27,1,"Korkie","M",nil," ","N","N"," "," "," "," ","Grey","Schnauzer",20],
        [28,1,"Emma","F",Date.new(2008,01,01)," ","Y","N"," "," "," "," ","White,Cream","Cocker Bichon",20],
        [29,1,"Murphy","M",Date.new(2014,04,01)," ","Y","N","Cypress Square Animal Clinic"," "," "," ","Black, Brown","Pembroke Corgi",20],
        [30,1,"Sydney","F",nil," ","N","Y","Larry White"," "," ","Good on grooming","White","Maltipoo",20],
        [31,1,"Harley","M",Date.new(2017,01,01)," ","Y","N","Tx Coalition"," "," "," ","Black","Lhasa",18],
        [32,1,"Pepe le Pew","M",nil," ","N","N"," "," "," ","Bossy","Black, Browm","Pomeranian",20],
        [32,1,"Valentine","M",nil," ","Y","Y"," ","713-291-1702"," ","Scared easily","Grey, White","Mini Schnauzer",20],
        [32,1,"Layla","F",nil," ","Y","Y","Dr. Ken"," "," "," ","Brown","Weiner dog",20],
        [32,1,"Chimmie","M",nil," ","N","Y"," "," "," "," ","Brown","Weiner dog",20],
        [33,1,"Bailey","F",Date.new(2017,01,01)," ","Y","N","Tanner Lakes"," "," "," ","White, Gray","Old English",20],
        [33,1,"Millie","F",Date.new(2010,01,01)," ","Y","N","Tanner Lakes"," "," "," ","White, Brown","Bishon",20],
        [34,1,"Coco","F",Date.new(2013,01,01)," ","N","N","St. Francis"," "," "," ","Tan","Terrier Mix",20],
        [34,1,"Callie","F",Date.new(2015,01,01)," ","N","Y","St. Francis"," "," "," ","Black,White","King Charles",20],
        [35,1,"Stanley","M",Date.new(2016,01,01)," ","Y","Y","Tanner Lakes"," "," ","Shy,noisy","Tan","Yorkie",20],
        [35,1,"Jake","M",Date.new(2015,01,01)," ","Y","N","Tanner Lakes"," "," ","Shy,noisy","Tan, White","Yorkie",20],
        [35,1,"Sara","F",Date.new(2017,01,01)," ","Y","N","Tanner Lakes"," "," ","Shy,noisy","Black","Yorkie",20],
        [36,1,"Pinky","F",nil," ","N","Y"," "," "," "," ","White, Black","Maltipoo",20],
        [37,1,"Cherry","F",Date.new(2016,01,01)," ","N","Y","Crossroads Vet"," "," "," ","Black","Aussiedoodle",20],
        [38,1,"Rylie","F",Date.new(2015,01,01)," ","Y","N","Jersey Village Animal Hospital"," "," "," ","Tan","Lab Mix",25],
        [39,1,"Barter","F",Date.new(2014,01,01)," ","Y","Y"," "," "," "," ","Tan","Pug",20],
        [40,1,"Jammy","M",Date.new(2015,01,01)," ","N","N","Dr. Martin Kaedle"," "," ","Noisy","White","Mini Schnauzer",20],
        [40,1,"Sterling","M",Date.new(2015,01,02)," ","N","Y","Dr. Martin Kaedle"," "," "," ","Gray","Mini Schnauzer",20],
        [41,1,"Cookie","M",Date.new(2012,01,01)," ","Y","N"," "," "," "," ","Brown","Yorkie Poo",16],
        [42,1,"Pixie","F",Date.new(2010,01,01)," ","N","Y"," "," "," "," ","Black, Tan","Chihuahua",7],
        [43,1,"Sunny","F",Date.new(2016,01,01)," ","N","Y","Kingsland Vet Clinic"," "," "," ","White","Poodle Mix",20],
        [43,1,"Jax","M",Date.new(2010,01,01)," ","Y","N","Kingsland Vet Clinic"," "," "," ","Grey","Pitbull",20],
        [44,1,"Kaysi","F",Date.new(2018,01,01)," ","Y","N"," "," "," "," ","Brown","Shih Tzu",20],
        [46,1,"Barkley","M",nil," ","Y","Y"," "," "," "," ","White","Maltese",20],
        [47,1,"Bruce","M",Date.new(2016,06,01)," ","Y","Y","Dr. Cheryl Morales"," "," "," ","Black","Lab, Pit, Rot",42],
        [48,1,"Pancho","M",Date.new(2014,11,01)," ","N","N"," "," "," "," ","Brown","Chihuahua",12],
        [49,1,"Lucky","M",Date.new(2018,01,01)," ","N","Y"," "," "," "," ","Tan","Maltese Mix",20],
        [50,1,"Corette","F",Date.new(2013,01,01)," ","Y","Y"," "," "," "," ","Blonde","Shih Tzu",12],
        [51,1,"Pooh Bear","M",Date.new(2017,11,01)," ","N","Y"," "," "," "," ","Golden","Golden Retriever",78]
        # [51,1,"Bud","M",nil," ","N","N"," "," "," ","Pooh Bear Family","Black, Tan","Yorkie",20],
        # [52,1,"Izzy","F",nil," ","N","Y","Longendauch Vet"," "," ","Scared of water","Black, Brown","German Shepherd Mix",20],
        # [53,1,"Leo","M",nil," ","Y","N"," "," "," "," ","Chocolate","Lab",50],
        # [54,1,"Lydia","F",Date.new(2011,12,01)," ","Y","N"," "," "," "," ","White","Golden Retriever",49],
        # [54,1,"Millie","F",Date.new(2005,12,01)," ","Y","Y"," "," "," "," ","Brown, Red","Golden Retriever",20],
        # [55,1,"Pillow","F",Date.new(2011,07,01)," ","N","N"," "," "," "," ","Brown, Red, White","Golden Retriever",20],
        # [56,1,"Baccarat","M",nil," ","N","N"," "," "," "," ","White","Shih Tzu",20],
        # [57,1,"Brownie","M",Date.new(2008,01,01)," ","Y","Y","Affordable Pet Care"," "," ","Bites when he is scared. Noisy","Black, Brown","Dachshund",20],
        # [58,1,"Jools","F",Date.new(2018,01,01)," ","Y","N","Canfel"," "," "," ","Tan","Terrier",20],
        # [58,1,"Emmie","F",nil," ","Y","Y","Canfel"," "," ","Little girl","Tan","Terrier mix",20],
        # [58,2,"Sadie","F",nil," ","Y","N","Wainwright"," ","Epileptic","In Heaven","Black","Pomapoo",20],
        # [59,1,"Xena","F",nil," ","N","Y"," "," "," ","Shy. Bites","Brown, White","Terrier Mix",20],
        # [59,1,"Griffin","M",Date.new(2019,01,01)," ","Y","N"," "," "," "," ","White","Terrier",20],
        # [60,1,"Bentley","M",Date.new(2018,02,01)," ","N","Y"," "," ","N/A"," ","White","Maltipoo",36],
        # [61,1,"Eliot","M",Date.new(2014,11,01)," ","N","Y","Hearthstone Clinic"," "," "," ","White","Westie",16],
        # [61,1,"Oliver","M",Date.new(2009,07,01)," ","Y","N"," "," "," "," ","White","Westie",20],
        # [62,1,"Prince","M",Date.new(2014,01,01)," ","Y","Y","Thrive"," "," "," ","Blonde","Maltipoo",20],
        # [62,1,"Lala","F",Date.new(2016,01,01)," ","Y","N"," "," "," "," ","Black, White","Maltese",20],
        # [63,1,"Jinx","F",Date.new(2017,11,01)," ","Y","Y","Lonestar Vetinary"," ","None"," ","Black","Cannecorso",45],
        # [64,1,"Sir Angus Hamilton","M",Date.new(2013,9,26)," ","Y","N"," "," "," ","Noisy, Shy, Doesn't like nails done","Brown","Scottie",26],
        # [64,1,"Dougal","M",Date.new(2018,05,01)," ","N","Y"," "," "," "," ","Black","Scottie",25],
        # [65,1,"Pita","F",Date.new(2017,06,01)," ","Y","Y"," "," "," "," ","Tan","Lab Mix",60],
        # [65,1,"Tahwi","F",Date.new(2017,06,02)," ","Y","N"," "," "," "," ","Tan","Lab, Pit",50],
        # [66,1,"Stevie","M",nil," ","N","Y","Dr. Smih Clay Rd"," ","Blind","Bites","Black","Shih Tzu",20],
        # [66,2,"Nellie","F",Date.new(2003,01,01)," ","N","N"," "," "," ","In Heaven","Brown","Chihuahua",20],
        # [66,2,"Punk","F",Date.new(2002,01,01)," ","N","Y"," "," "," Arthritic, Epileptic","In Heaven ","Tan","Chihuahua",20],
        # [66,1,"Daisy","F",nil," ","Y","N"," "," "," "," ","Tan, White","Terrier Mix",20],
        # [66,1,"Valentina","F",nil," ","Y","Y"," "," "," ","Shy","Brown, White","Shiba Inu",20],
        # [66,1,"Milo","M",Date.new(2014,8,01)," ","N","N"," "," "," "," ","White, Grey","Bulldog Mix",20],
        # [45,1,"Chibi","F",Date.new(2018,01,01)," ","Y","Y","Tanner Lakes","713-937-4484"," "," ","Black, Brown","Mini Dachshund",20],
        # [67,1,"Angel","F",nil," ","Y","Y"," "," "," "," ","White","Bichon Poodle",20],
        # [68,1,"Cooper","M",Date.new(2013,01,01)," ","N","Y","Glen Cairn Animal Clinic"," ","No"," ","Black","Lab",75],
        # [68,1,"Mija","F",Date.new(2010,01,01)," ","Y","Y","Clen Cairn Animal Clinic"," ","No"," ","Black","Lab",80],
        # [69,1,"Sawyer","M",Date.new(2010,01,01)," ","N","N","Natalie Goldberger"," "," "," ","Gold","Snoodle",22],
        # [70,1,"Bruno","F",Date.new(2012,01,01)," ","N","N","Kawws"," "," "," ","White","Poodle",20],
        # [71,1,"Teddy","M",nil," ","Y","Y"," ","832-549-3123"," "," ","Brown, Black","Chihuahua Mix",20],
        # [74,1,"Sysco","M",Date.new(2009,01,01)," ","N","Y","Tanner Lakes"," "," "," ","Grey","Havanese",20],
        # [74,1,"Emerson","M",Date.new(2018,01,01)," ","N","N","Tanner Lakes"," "," ","Shy","Brown","Yorkie",20],
        # [72,1,"Izzy","F",nil," ","Y","Y"," "," "," ","Very sweet","Brown, White","Cockapoo",20],
        # [73,1,"Tien Tien","F",Date.new(2002,01,01)," ","Y","Y","Natalie Goldberger"," "," ","Can't stand well","Black","Shih Tzu",20],
        # [75,1,"Tiger","M",nil," ","Y","Y"," "," "," "," ","Brown","Terrier Mix",20],
        # [76,1,"Roxie","F",Date.new(2004,01,01)," ","Y","N","Pelton Hearthstone"," "," ","Thyroid","Black, White","Multi",20],
        # [77,1,"Sadie","F",Date.new(2012,01,01)," ","Y","Y","Animal Medical Center"," "," "," ","Brown, White","Yorky",20],
        # [78,1,"Peach","F",Date.new(2013,01,01)," ","N","N","Northpointe Animal Hospital"," ","Heart"," ","Brown, White","Cavalier",20],
        # [78,1,"Luigi","M",Date.new(2014,01,01)," ","N","Y","Northpointe Animal Hospital"," "," "," ","White","Maltese",20],
        # [79,1,"Luna Rose","F",Date.new(2017,01,01)," ","Y","Y"," "," ","None"," ","Brindle","Yorkie Poo",5],
        # [80,1,"Monty","M",Date.new(2011,01,01)," ","N","N","Bingle Vet"," "," "," ","White","Coton",15],
        # [81,1,"Bella ","F",Date.new(2013,04,01)," ","Y","N","Longenbough Vet"," ","Rescue Sensitive"," ","Brown, Red","Yorkie",5],
        # [82,1,"Christian","M",nil," ","Y","Y"," "," "," "," ","White","Maltese",20],
        # [83,1,"Molly","F",Date.new(2015,9,01)," ","N","N"," "," "," "," ","White","Bichon Shitzu",20],
        # [83,1,"Hercules","M",Date.new(2017,10,01)," ","N","N"," "," "," "," ","Grey, Black","Bulldog",64],
        # [84,1,"Dixie","F",Date.new(2014,01,01)," ","Y","Y","Cyfair Pet Clinic"," "," "," ","Black","Lab Mix",60],
        # [85,1,"Maxwell","M",Date.new(2017,06,01)," ","Y","Y","VCA Clinic"," "," "," ","S & P","Cairn Terrier",20],
        # [85,1,"Zazou","F",Date.new(2013,06,01)," ","Y","Y"," "," "," "," ","Black","Cairn Terrier",20],
        # [85,1,"Phoebe","F",Date.new(2006,06,01)," ","Y","N"," "," "," ","Age related sight/ hearing","Black","Poodle",20],
        # [86,1,"Alexa","F",Date.new(2018,01,01)," ","N","N","Texa Vet"," "," "," ","White","Maltese",13],
        # [87,1,"Pumkin","F",Date.new(2011,01,01)," ","N","Y","Crossroads"," "," ","Sweet","White","Maltipoo",20],
        # [87,1,"Maxie","F",Date.new(2016,01,01)," ","N","Y","Crossroads"," "," "," ","White","Maltipoo",23],
        # [88,1,"Ally","M",nil," ","Y","N","Dr. Betty Holbrook; Cypress Falls Animal Clinic"," "," ","Shy, Doesn't like other dogs, showing teeth","Grey, Black","Irish Terrier Mix",20],
        # [89,1,"Tiny","M",Date.new(2015,05,01)," ","Y","N"," "," ","N/A"," ","white","Maltipoo",20],
        # [89,1,"Luna","F",Date.new(2015,05,01)," ","Y","N"," "," ","N/A"," ","White","Maltipoo",8],
        # [90,1,"Tucker","M",Date.new(2013,01,01),"N","Y","Y","Jersey"," ","NA"," ","tan","Dauchsand",114],
        # [91,1,"Hopper","M",Date.new(2009,01,01)," ","N","Y","NCA Spring Branch"," ","paws/ears","Hates nails and scissoring; Eon Only","Brown","Shih Tzu",20],
        # [91,1,"Chryssy","F",Date.new(2007,01,01)," ","Y","N","VCA Clinic Spring Branch"," ","Deaf"," ","White, Grey","Maltipoo",20],
        # [91,1,"Meeka","M",nil," ","Y","N"," "," "," ","Noisy","Brown, Black","Mini Dachshund",20],
        # [92,1,"Tucker","M",Date.new(2015,04,01)," ","Y","Y","The Corner Vet","832-818-4671"," ","Shy; Scared of everything ; Mohawk","Grey, White","Schnauzer",20],
        # [93,1,"Sherv","M",Date.new(2015,04,9)," ","N","Y"," ","832-212-6263"," "," ","Black, Brown","Pit, Rotweiler",20],
        # [94,1,"Cosette","F",Date.new(2019,01,01)," ","Y","Y","Memorial Vet"," "," ","Shorter Jaw Line; doesn't like face be heldd; sweet","Cream","Doodle",39],
        # [95,1,"Bear","M",nil," ","Y","Y","Forest West"," "," "," ","Black","Schnauzer",20],
        # [95,1,"Bandit","M",nil," ","N","Y","Forest West"," "," "," ","Salt & Pepper","Schnauzer",20],
        # [96,1,"Lola","F",Date.new(2012,01,01)," ","N","N","Jersey Village Animal Hospital "," "," "," ","White ","Cavalier",14],
        # [97,1,"Hannah","F",Date.new(2010,8,01),"Chicken","Y","N","Dr. Smith; Clay Road Animal Hospital"," ","Takes Synthroid (Meds)","Scared of thunder","Salt and Pepper","Schnoodle",20],
        # [97,1,"Sheba","F",Date.new(2010,8,01)," ","Y","Y"," "," "," ","Alaskan Husky or Malamute","White, Grey","Alaskan Husky",70],
        # [98,1,"SnuffBaby1","M",nil," ","N","N"," "," "," ","Drama queen with nails","Grey, Brown","Snorkie",20],
        # [98,1,"SnuffBaby2","M",Date.new(2012,01,01)," ","Y","N"," "," "," "," ","Grey, Brown","Yorkie",20],
        # [98,1,"SnuffBaby3","F",Date.new(2012,01,01)," ","Y","Y"," "," "," "," ","Grey, Brown","Yorkie",20],
        # [99,1,"Bailey","F",Date.new(2017,06,01)," ","N","Y","Cypress Falls Animal Hospital"," "," ","Noisy","Brown","Terrier",20],
        # [100,1,"Axel","M",Date.new(2017,01,01)," ","Y","Y","Hearthstone Animal Clinic"," "," "," ","White, Grey","Australian Shepard",20],
        # [100,1,"Jara","F",Date.new(2015,01,01)," ","Y","Y","Hearthstone Animal Clinic"," "," "," ","White, Grey, Brown-muzzle","Australian Shepard",20]
    ]



    pets.each do | customer_id, pet_status_id, name, gender, birthdate, allergies, sn, treat, vet_name, vet_phone, med_issues, notes, color, breed, weight|
        Pet.create( customer_id: customer_id, pet_status_id: pet_status_id, pet_name: name, pet_gender: gender, pet_birthdate: birthdate, pet_allergies: allergies,
                    spayed_neutered: sn, pet_treat: treat, vet_name: vet_name, vet_phone: vet_phone, pet_medical_issues: med_issues, pet_notes: notes, pet_color: color,
                    pet_breed: breed, pet_weight: weight)
    end

